<?php
namespace frontend\controllers\common;

use Yii;
use yii\web\Controller;

/**
 * Created by PhpStorm.
 * User: bi
 * Date: 2020/7/27
 * Time: 上午11:22
 */
class BaseController extends Controller{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if(Yii::$app->user->isGuest){
            return $this->redirect('/');
        }

    }
}